// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentKind } from "./AttachmentKind";

/**
 * A file or link attached to a task.
 */
export type Attachment = { id: string, kind: AttachmentKind, 
/**
 * Where the attachment lives: the URL for a link, the file location for a
 * file.
 */
url: string, 
/**
 * Label shown instead of the raw location.
 */
name?: string | null, };
