// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where an export landed, and how much of it there was.
 *
 * `path` is absent for the one outcome that is neither success nor failure: no
 * task carried a date, so there was nothing to put in a file and no file was
 * written. Saying that with an absent path rather than an error keeps "nothing
 * to export" out of the error channel, where the view layer would have to tell
 * it apart from a disk that refused the write.
 *
 * `unrepeatable_recurrences` is how many of those events carry a repeat rule
 * RFC 5545 cannot express and therefore appear once instead of repeating. It
 * travels with the result so the view layer can say so: a repeat the file drops
 * without a word is a repeat the user believes they exported.
 */
export type CalendarExport = { path: string | null, eventCount: number, unrepeatableRecurrences: number, };
