// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A habit's streak and the recent scheduled days it could still be checked in
 * on.
 *
 * `streak` is how many scheduled days it has been kept up in a row; `makeup` are
 * the recent days that fell due unchecked, most recent first, for the row's
 * make-up buttons. Empty for a rule that is not a daily or weekly habit.
 */
export type HabitProgress = { streak: number, makeup: Array<string>, };
