// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecurrenceCalendar } from "./RecurrenceCalendar";
import type { RecurrenceFrequency } from "./RecurrenceFrequency";
import type { Weekday } from "./Weekday";

/**
 * How a task repeats.
 *
 * The rule is flat rather than a nested variant per frequency because it is
 * stored, synced and edited as one unit; the combinations that do not make
 * sense are rejected by `validate` instead of being made unrepresentable, which
 * keeps the generated TypeScript a single object type.
 */
export type RecurrenceRule = { frequency: RecurrenceFrequency, 
/**
 * Repeat every `interval` units of `frequency`.
 */
interval: number, 
/**
 * For weekly rules, the days it lands on (e.g. Monday/Wednesday/Friday).
 * Empty means "the same weekday as the task's due date".
 */
weekdays: Array<Weekday>, 
/**
 * For monthly rules, the day of the month (1–31).
 */
monthDay?: number | null, 
/**
 * For monthly rules, "the last day of the month" — the one position that
 * cannot be written as a fixed day number.
 */
onLastDay: boolean, 
/**
 * Which calendar the rule is counted in.
 */
calendar: RecurrenceCalendar, 
/**
 * Local date the repetition stops on, inclusive.
 */
until?: string | null, 
/**
 * Number of occurrences the repetition stops after.
 */
count?: number | null, };
