// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One step of a task's checklist.
 */
export type Subtask = { id: string, title: string, done: boolean, };
