// Generated by ts-rs from crates/contracts. Do not edit manually.
import type { TodoSyncOperation } from "./TodoSyncOperation";

export type SyncRequest = {
  deviceId: string;
  cursor: number;
  operations: Array<TodoSyncOperation>;
};
