// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TodoSyncOperation } from "./TodoSyncOperation";

export type SyncRequest = { deviceId: string, cursor: number, operations: Array<TodoSyncOperation>, };
