// Generated by ts-rs from crates/contracts. Do not edit manually.
import type { TodoSyncChange } from "./TodoSyncChange";

export type SyncResponse = {
  acknowledgedOperationIds: Array<string>;
  changes: Array<TodoSyncChange>;
  nextCursor: number;
  serverTime: string;
};
