// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TodoSyncChange } from "./TodoSyncChange";

export type SyncResponse = { acknowledgedOperationIds: Array<string>, changes: Array<TodoSyncChange>, nextCursor: number, serverTime: string, };
