// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attachment } from "./Attachment";
import type { RecurrenceRule } from "./RecurrenceRule";
import type { Subtask } from "./Subtask";
import type { TodoStatus } from "./TodoStatus";

/**
 * A task.
 *
 * Every field beyond the original six is optional or list-valued with a serde
 * default, which is what keeps a payload written by an earlier build readable:
 * the fields it never knew about simply come back empty. `deny_unknown_fields`
 * only bites in the other direction — a payload from a *newer* build — and the
 * repository has no version negotiation by design (AGENTS.md), so bindings are
 * regenerated and callers are updated together with the contract.
 */
export type Todo = { id: string, title: string, status: TodoStatus, createdAt: string, completedAt: string | null, 
/**
 * When the task was archived: "done long enough that it need not be seen
 * any more".
 *
 * A field of its own rather than a third `TodoStatus` variant, because
 * archiving and completing are orthogonal. A status can only say one thing
 * at a time, so folding the two together would lose "it was completed, and
 * then archived" — and every reader of the status (the open count, the
 * completed set, the statistics still to come) would have to be redefined
 * to keep meaning what it means today.
 */
archivedAt?: string | null, dueDate?: string | null, reminderAt?: string | null, 
/**
 * Free-text description, searchable alongside the title.
 */
notes?: string | null, 
/**
 * Local date the task becomes actionable; before it the task stays out of
 * the way instead of demanding attention.
 */
startDate?: string | null, 
/**
 * Start of a timed block, as an instant (the due date stays a plain date).
 */
startsAt?: string | null, 
/**
 * End of a timed block; only meaningful together with `starts_at`.
 */
endsAt?: string | null, 
/**
 * Planned effort in minutes, compared against recorded focus time later.
 */
estimatedMinutes?: number | null, 
/**
 * Repeat rule; absent means the task happens once.
 */
recurrence?: RecurrenceRule | null, 
/**
 * The list this task belongs to; absent means the inbox.
 */
listId?: string | null, 
/**
 * Eisenhower axes. Kept separate and tri-state on purpose: `None` is "the
 * user has not said", which is what lets the urgency default be inferred
 * from the due date without overwriting a deliberate choice.
 */
important?: boolean | null, urgent?: boolean | null, 
/**
 * Manual position within a list. Fractional so a drag between two rows
 * only writes the row that moved.
 */
sortOrder?: number | null, 
/**
 * Tags applied to this task, by tag id.
 */
tagIds: Array<string>, 
/**
 * Checklist inside the task; the order of the vector is the display order.
 */
subtasks: Array<Subtask>, 
/**
 * Files and links hanging off the task.
 */
attachments: Array<Attachment>, 
/**
 * Tasks that must be done before this one.
 */
dependsOn: Array<string>, };
