// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TodoStatus } from "./TodoStatus";

export type TodoPatch = { title?: string, status?: TodoStatus, dueDate?: string | null, completedAt?: string | null, };
