// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TodoStatus } from "./TodoStatus";

export type Todo = { id: string, title: string, status: TodoStatus, createdAt: string, completedAt: string | null, dueDate?: string | null, reminderAt?: string | null, };
