// Generated by ts-rs from crates/contracts. Do not edit manually.
import type { SyncOperationKind } from "./SyncOperationKind";
import type { TodoPatch } from "./TodoPatch";

export type TodoSyncOperation = {
  operationId: string;
  todoId: string;
  kind: SyncOperationKind;
  occurredAt: string;
  patch?: TodoPatch;
};
