// Generated by ts-rs from crates/contracts. Do not edit manually.
import type { TodoStatus } from "./TodoStatus";

export type Todo = {
  id: string;
  title: string;
  status: TodoStatus;
  createdAt: string;
  completedAt: string | null;
};
