// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attachment } from "./Attachment";
import type { RecurrenceRule } from "./RecurrenceRule";
import type { Reminder } from "./Reminder";
import type { Subtask } from "./Subtask";
import type { TodoStatus } from "./TodoStatus";

/**
 * The fields one sync operation changes.
 *
 * An absent field means "unchanged"; a present one replaces the stored value,
 * list-valued fields included (a tag set is sent whole, not as a diff).
 *
 * Nullable fields are `Option<Option<T>>` rather than `Option<T>` so that
 * "leave it alone" and "clear it" are different values instead of the same one:
 * the outer option is whether the patch mentions the field, the inner one is
 * what it sets it to. Without the distinction every optional field could be
 * filled in and never emptied again — a clear left home as `null`, arrived as
 * "unchanged", and the other devices went on showing the old value.
 */
export type TodoPatch = { title?: string, status?: TodoStatus, dueDate?: string | null, completedAt?: string | null, 
/**
 * Nested like every other nullable field, and for the sharpest instance of
 * the reason: restoring an archived task *is* clearing this field, so a
 * flat option would send that restore as "unchanged" and the task would
 * stay archived on every other device.
 */
archivedAt?: string | null, notes?: string | null, startDate?: string | null, startsAt?: string | null, endsAt?: string | null, estimatedMinutes?: number | null, recurrence?: RecurrenceRule | null, listId?: string | null, important?: boolean | null, urgent?: boolean | null, sortOrder?: number | null, 
/**
 * The whole reminder list, sent as one value like the tag set rather than as
 * a diff: absent leaves the reminders alone, an empty list clears them. This
 * is the shape the single `reminder_at` three-state option gave way to — a
 * list field replaces wholesale, so "no reminders" is `[]`, not the `null`
 * the old option carried.
 */
reminders?: Array<Reminder>, tagIds?: Array<string>, subtasks?: Array<Subtask>, attachments?: Array<Attachment>, dependsOn?: Array<string>, 
/**
 * The whole set of scheduled dates a habit has been checked in on, sent as
 * one value like the tag set rather than as a diff.
 */
checkIns?: Array<string>, };
